const en_el_consultorio = [
    ["la clínica", "clinic"],
    ["el consultorio", "doctor's office"],
    ["el/la dentista", "dentist"],
    ["el examen médico", "physical exam"],
    ["la farmacia", "pharmacy"],
    ["el hospital", "hospital"],
    ["la operación", "operation"],
    ["la sala de emergencias", "emergency room"],
    ["el cuerpo", "body"],
    ["el oído", "(sense of) hearing; inner ear"],
    ["el accidente", "accident"],
    ["la salud", "health"],
    ["el sintoma", "symptom"],
    ["caerse", "to fall (down) "],
    ["darse con", "to bump into; to run into "],
    ["doler (o:ue)", "to hurt "],
    ["enfermarse", "to get sick "],
    ["estar enfermo/a", "to be sick "],
    ["poner una inyección", "to give an injection "],
    ["recetar", "to prescribe "],
    ["romperse (la pierna)", "to break (one's leg) "],
    ["sacar(se) un diente", "to have a tooth removed "],
    ["sufrir una enfermedad", "to suffer an illness "],
    ["torcerse (o:ue) (el tobillo)", "to sprain (one's ankle) "],
    ["toser", "to cough "],
    ["el dolor (de cabeza)", "(head)ache; pain"],
    ["la gripe", "flu"],
    ["el resfriado", "cold"],
    ["la tos", "cough"],
    ["congestionado/a", "congested; stuffed up"],
    ["embarazada", "pregnant"],
    ["grave", "grave; serious"],
    ["mareado/a", "dizzy; nauseated"],
    ["médico/a", "medical"],
    ["saludable", "healthy"],
    ["sano/a", "healthy"],
    ["tener dolor (m.)", "to have pain "],
    ["tener fiebre", "to have a fever "],
    ["el antibiótico", "antibiotic"],
    ["la aspirina", "aspirin"],
    ["la pastilla", "pill; tablet"],
    ["la receta", "prescription"],
    ["el paciente", "patient"],
    ["la cabeza", "head"],
    ["la oreja", "ear"],
    ["el cuello", "neck"],
    ["la boca", "mouth"],
    ["la garganta", "throat"],
    ["el estómago", "stomach"],
    ["la naríz", "nose"],
    ["el corazón", "heart"],
    ["el dedo", "finger"],
    ["la rodilla", "knee"],
    ["el pie", "foot"],
    ["el dedo de pie", "toe"],
    ["el radiografía", "xray"],
    ["el hueso", "bone"],
    ["la enfermera", "nurse"],
    ["estornuda", "sneeze"],
    ["toma la temperatura", "taking temperature"],
    ["el brazo", "arm"],
]


const imperfect_tense = [
    ["Entendíamos japonés.", "We used to understand Japanese."],
    ["El camarero les servía el café.", "The waiter was serving them coffee."],
    ["A Javier le dolía el tobillo.", "Javier's ankle was hurting."],
    ["¿Qué te pasó?", "What happened to you?"],
    ["Me torcí el tobillo.", "I sprained my ankle."],
    ["¿Dónde vivías de niño?", "Where did you live as a child?"],
    ["Vivía en San José.", "I lived in San José."],
    ["Íbamos al parque los domingos.", "We used to go to the park on Sundays."],
    ["Yo leía mientras él estudiaba.", "I was reading while he was studying."],
    ["Era alto y guapo.", "He was tall and handsome."],
    ["Quería mucho a su familia.", "He loved his family very much."],
    ["Eran las tres y media.", "It was 3:30."],
    ["Los niños tenían seis años.", "The children were six years old."],
]


const constructions_with_se = [
    ["Se habla español en Costa Rica.", "Spanish is spoken in Costa Rica."],
    ["Se hacen operaciones aquí.", "They perform operations here."],
    ["Se puede leer en la sala de espera.", "You can read in the waiting room."],
    ["Se necesitan medicinas enseguida.", "They need medicine right away."],
    ["Se me perdió el teléfono de la farmacia.", "I lost the pharmacy's phone number."],
    ["Se nos olvidaron los pasajes.", "We forgot the tickets."],
    ["El médico dejó caer la aspirina.", "The doctor dropped the aspirin."],
    ["A mí se me cayeron los cuadernos.", "I dropped the notebooks."],
    ["Al paciente se le perdió la receta.", "The patient lost his prescription."],
    ["A ustedes se les quedaron los libros en casa.", "You left the books at home."],
]


const preterite_and_imperfect = [
    ["Sandra se rompió la pierna.", "Sandra broke her leg."],
    ["Fueron a Buenos Aires ayer.", "They went to Buenos Aires yesterday."],
    ["La película empezó a las nueve.", "The movie began at nine o'clock."],
    ["Ayer terminé el proyecto para la clase de química.", "Yesterday I finished the project for chemistry class."],
    ["La doctora me miró los oídos, me hizo unas preguntas y escribió la receta.", "The doctor looked in my ears, asked me some questions, and wrote the prescription."],
    ["Me di con la mesa me caí y me lastimé el pie.", "I bumped into the table, I fell, and I injured my foot."],
    ["Sandra esperaba al doctor.", "Sandra was waiting for the doctor."],
    ["El médico se preocupaba por sus pacientes.", "The doctor worried about his patients."],
    ["Cuando era joven, jugaba al tenis.", "When I was young, I used to play tennis."],
    ["De niño, Eduardo se enfermaba con mucha frecuencia.", "As a child, Eduardo used to get sick very frequently."],
    ["La chica quería descansar. Se sentía mal y tenía dolor de cabeza.", "The girl wanted to rest. She felt ill and has a headache."],
    ["Ellos eran altos y tenían ojos verdes.", "They were tall and had green eyes."],
    ["Estábamos felices de ver a la familia.", "We were happy to see our family."],
    ["Miraba la tele cuando sonó el teléfono.", "I was watching TV when the phone rang."],
    ["Felicia leía el periódico cuando llegó Ramiro.", "Felicia was reading the newspaper when Ramiro arrived."],
]

const adverbs = [
    ["Maira dibuja maravillosamente.", "Maira draws wonderfully."],
    ["Sergio está casi siempre ocupado.", "Sergio is almost always busy."],
    ["La cita era a las dos, pero llegamos tarde.", "The appointment was at two o'clock, but we were late."],
    ["El problema fue que ayer se nos dañó el despertador.", "The problem was that yesterday our alarm clock was damaged."],
    ["La recepcionista no se enojó porque sabe que normalmente llego a tiempo.", "The receptionist did not get angry because she knows I usually arrive on time."],
    ["Por lo menos el doctor estaba listo.", "At least the doctor was ready."],
    ["Apenas tuvimos que esperar cinco minutos.", "We barely had to wait five minutes."],
    ["El doctor dijo que nuestra hija Claire necesitaba cambiar su rutina diaria inmediatamente.", "The doctor said that our daughter Claire needed to change her daily routine immediately."],
    ["El doctor nos explicó bien las recomendaciones del Secretario de Sanidad sobre la salud de los jóvenes.", "The doctor explained to us the recommendations of the Minister of Health regarding the health of young people."],
    ["Afortunadamente nos dijo que Claire estaba bien, pero tenía que hacer más ejercicio y comer mejor.", "Fortunately he told us that Claire was doing well, but she needed to exercise more and eat better."],
]

const la_tecnología = [
    ["la cámara digital/de video", 'digital (video) camera'],
    ['el canal', '(TV) channel'],
    ['el cibercafé', 'cybercafé'],
    ["el correo de voz", "voice mail"],
    ["el estéreo", "stereo"],
    ["el fax", "fax (machine)"],
    ["la pantalla táctil", "touch screen"],
    ["el reproductor de CD", "CD player"],
    ["la televisión por cable", "cable television"],
    ["el video", "video"],
    ["el archivo", "file"],
    ["la arroba", "@ symbol"],
    ["el blog", "blog"],
    ["la conexión inalámbrica", "wireless connection"],
    ["la dirección electrónica", "e-mail address"],
    ["Internet", "Internet"],
    ["el mensaje de texto", "text message"],
    ["la página principal", "home page"],
    ["el programa de computación", "software"],
    ["la red", "network; Web"],
    ["el sitio web", "website"],
    ["apagar", "to turn off"],
    ["borrar", "to erase"],
    ["descargar", "to download"],
    ["escanear", "to scan"],
    ["funcionar", "to work"],
    ["grabar", "to record"],
    ["guardar", "to save"],
    ["imprimir", "to print"],
    ["llamar", "to call"],
    ["navegar (en Internet)", "to surf (the Internet)"],
    ["poner, prender", "to turn on"],
    ["sonar (o:ue)", "to ring"],
    ["descompuesto/a", "not working; out of order"],
    ["lento/a", "slow"],
    ["lleno/a", "full"],
    ["el televisor", "television"],
    ["la pantalla", "the screen"],
    ["el reproductor de DVD", "DVD player"],
    ["la impresora", "printer"],
    ["la computadora (portátil)", "computer (laptop)"],
    ["el monitor", "the monitor"],
    ["el ratón", "(computer) mouse"],
    ["el (teléfono) celular", "cell phone"],
    ["el teclado", "keyboard"],
    ["el cederrón", "CD (CD-ROM)"],
    ["el control remoto", "the remote control"],
    ["el reproductor de MP3", "the MP3 player"],
    ["el disco compacto", "compact disc"],
    ["la autopista, la carretera", "highway"],
    ["la calle", "street"],
    ["la circulación, el tráfico", "traffic"],
    ["el garaje, el taller (mecánico)", "(mechanic's) garage; repair shop"],
    ["la licencia de conducir", "driver's license"],
    ["el/la mecánico/a", "mechanic"],
    ["la policía", "police (force)"],
    ["la velocidad máxima", "speed limit"],
    ["arrancar", "to start"],
    ["arreglar", "to fix; to arrange"],
    ["bajar(se) de", "to get off of/out of (a vehicle)"],
    ["conducir manejar", "to drive"],
    ["estacionar", "to park"],
    ["parar", "to stop"],
    ["subir(se) a", "to get on/into (a vehicle)"],
    ["el capó, el cofre", "the hood (of a car)"],
    ["el parabrisas", "the windshield"],
    ["Revisa el aceite. (revisar)", "He checks the oil (to check)"],
    ["el carro, el coche", "car"],
    ["Llena el tanque. (llenar)", "He fills the tank (to fill)"],
    ["el radio", "the radio (physical object)"],
    ["la gasolina", "the gasoline"],
    ["el baúl", "the trunk"],
    ["el navegador GPS", "the GPS navigator"],
    ["el volante", "the steering wheel"],
    ["la llanta", "the tire"],
]

const familiar_commands = [
    ["Guarda el documento antes de cerrarlo.", "Save the document before closing it."],
    ["Imprime tu tarea para la clase de inglés.", "Print your homework for English class."],
    ["¡Sal ahora mismo!", "Leave at once!"],
    ["Haz los ejercicios.", "Do the exercises."],
    ["Ve al cibercafé con Yolanda.", "Go to the cybercafé with Yolanda."],
    ["Ve ese programa... es muy interesante.", "See that program... it's very interesting."],
    ["Héctor, no pares el carro aquí.", "Héctor, don't stop the car here."],
    ["No prendas la computadora todavía.", "Don't turn on the computer yet."],
    ["No pongas el cederrón en la computadora.", "Don't put the CD-ROM in the computer."],
    ["No conduzcas tan rápido.", "Don't drive so fast."],
    ["No pierdas tu celular.", "Don't lose your cell phone."],
    ["No vuelvas a esa gasolinera.", "Don't go back to that gas station."],
    ["No repitas las instrucciones.", "Don't repeat the instructions."],
]

const por_and_para = [
    ["La excursión nos llevó por el centro.", "The tour took us through downtown."],
    ["Mis amigos van para el estadio.", "My friends are going to the stadium."],
    ["Ana navegó la red por dos horas.", "Ana surfed the net for two hours."],
    ["Tengo que escribir un esayo para mañana.", "I have to write an essay by tomorrow."],
    ["Llegué a casa tarde por el tráfico.", "I got home late because of the traffic."],
    ["Estoy preparando una sorpresa para Eduardo.", "I'm preparing a surprise for Eduardo."],
    ["Pasamos por el parque y por el rio.", "We passed by the park and along the river."],
    ["Estuve en la Patagonia por un mes.", "I was in Patagonia for a month."],
    ["Lo hizo por su familia.", "She did it on behalf of her family."],
    ["Vengo por ti a las ocho.", "I'm coming for you at eight."],
    ["Manuel fue por su cámara digital.", "Manuel went in search of his digital camera."],
    ["Ellos viajan por la autopista.", "They travel by (by way of) the highway."],
    ["Le di dinero por el reproductor de MP3.", "I gave him money for the MP3 player."],
    ["José manejaba a 120 kilómetros por hora.", "José was driving 120 kilometers per hour."],
    ["Salimos para Córdoba el sábado.", "We are leaving for Córdoba on Saturday."],
    ["Él va a arreglar el carro para el viernes.", "He will fix the car by Friday."],
    ["Juan estudia para (ser) mecánico.", "Juan is studying to be a mechanic."],
    ["Es una llanta para el carro.", "It's a tire for the car."],
    ["Compré una impresora para mi abuelo.", "I bought a printer for my grandfather."],
    ["Para un joven, es desmasiado serio.", "For a young person, he is too serious."],
    ["Para mí, esta lección no es difícil.", "For me, this lesson isn't difficult."],
    ["Sara trabaja para Telecom Argentina.", "Sara works for Telecom Argentina."],
    ["Caminé por el parque.", "I walked through the park."],
    ["Caminé para el parque.", "I walked to (toward) the park."],
    ["Trabajó por su padre.", "He worked for (in place of) his father."],
    ["Trabajó para su padre.", "He worked for his father('s company)."],
]

const reciprocal_reflexives = [
    ["Luis y Marta se miran en el espejo.", "Luis and Marta look at themselves in the mirror."],
    ["Luis y Marta se miran.", "Luis and Marta look at each other."],
    ["Cuando nos vimos en la calle, nos abrazamos.", "When we saw each other on the street, we hugged (one another)"],
    ["Nos ayudamos cuando usamos la computadora.", "We help each other when we use the computer."],
    ["Ustedes se van a encontrar en el cibercafé, ¿no?", "You are meeting (each other) at the cybercafé, right?"],
    ["Las amigas se saludaron y se besaron", "The friends greeted each other and kissed (one another)."],
    ["Laura y Elián se conocían bien.", "Laura and Elián knew each other well."],
    ["Laura y Elián se miraban con amor", "Laura and Elián looked at each other with love."],
    ["Laura y Elián se entendían bien.", "Laura and Elián understood each other well."],
    ["Laura y Elián se hablaban todas las noches por teléfono.", "Laura and Elián talked to each other every night on the phone."],
    ["Laura y Elián se ayudaban con sus problemas.", "Laura and Elián helped each other with their problems."],
]

const stressed_possessive_adjectives_and_pronouns = [
    ["Juancho es un amigo mío.", "Juancho is a friend of mine."],
    ["Ella es una compañera nuestra.", "She is a classmate of ours."],
    ["Aquí está mi coche. ¿Dónde está el tuyo?", "Here's my car. Where is yours?"],
    ["El mío está en el taller de mi hermano.", "Mine is at my brother's garage."],
    ["¿Tienes las revistas de Carlos?", "Do you have Carlos' magazines?"],
    ["No, pero tengo las nuestras.", "No, but I have ours."],
    ["Una amiga suya vive en Mendoza.", "A friend of hers lives in Mendoza."],
    ["¿Me prestas la computadora tuya?", "Can I borrow your computer?"],
    ["El coche suyo nunca funciona bien.", "Her car never works properly."],
    ["No nos interesan los problemas suyos.", "We are not interested in your problems."],
    ["Yo quiero la cámara digital más ahora mismo.", "I want the digital camera more right now."],
    ["Unos amigos nuestros manejan como locos.", "Some friends of ours drive like crazy."],
]

const la_vivienda = [
    ["las afueras", "suburbs; outskirts"],
    ["el alquiler", "rent (payment)"],
    ["el ama (m., f.) de casa", "housekeeper; caretaker"],
    ["el barrio", "neighborhood"],
    ["el edificio de apartamentos", "apartment building"],
    ["el/la vecino/a", "neighbor"],
    ["la vivienda", "housing"],
    ["el balcón", "balcony"],
    ["la entrada", "entrance"],
    ["la escalera", "stairs; stairway"],
    ["el garaje", "garage"],
    ["el jardin", "garden; yard"],
    ["el patio", "patio; yard"],
    ["el sótano", "basement; cellar"],
    ["la cafetera", "coffee maker"],
    ["el electrodoméstico", "electrical appliance"],
    ["el horno (de microondas)", "(microwave) oven"],
    ["la lavadora", "washing machine"],
    ["la luz", "light; electricity"],
    ["la secadora", "clothes dryer"],
    ["la tostadora", "toaster"],
    ["el cartel", "poster"],
    ["la mesita de noche", "night stand"],
    ["los muebles", "furniture"],
    ["alquilar", "to rent"],
    ["mudarse", "to move (from one house to another)"],
    ["arreglar", "to neaten; to straighten up"],
    ["barrer el suelo", "to sweep the floor"],
    ["cocinar", "to cook"],
    ["ensuciar", "to get (something) dirty"],
    ["hacer quehaceres domésticos", "to do household chores"],
    ["lavar (el suelo, los platos)", "to wash (the floor, the dishes)"],
    ["limpiar la casa", "to clean the house"],
    ["planchar (la ropa)", "to iron (the clothes)"],
    ["quitar la mesa", "to clear the table"],
    ["quitar el polvo", "to dust"],
    ["la cómoda", "dresser"],
    ["el armario", "cupboard"],
    ["hace la cama. (hacer)", "she makes the bed"],
    ["el cuadro/la pintura", "painting"],
    ["el altillo", "attic"],
    ["el dormitorio", "bedroom"],
    ["la almohada", "pillow"],
    ["la manta", "blanket"],
    ["la sala", "room"],
    ["las cortinas", "curtains"],
    ["la lámpara", "lamp"],
    ["la mesita", "small table / stand"],
    ["el sofá", "sofa"],
    ["la alfombra", "rug"],
    ["Pasa la aspiradora (pasar)", "He vacuums."],
    ["la pared", "wall"],
    ["Sacude los muebles. (sacudir)", "dust the furniture"],
    ["el estante", "the shelf"],
    ["el sillón", "armchair"],
    ["la oficina", "office"],
    ["la cocina", "kitchen"],
    ["el regrigerador", "refrigerator"],
    ["el congelador", "freezer"],
    ["la cocina, la estufa", "stove"],
    ["el horno", "oven"],
    ["el lavaplatos", "dishwasher"],
    ["Saca la basura. (sacar)", "He takes out the trash."],
    ["el comedor", "dining room"],
    ["Pone la mesa. (poner)", "She sets the table."],
    ["el vaso", "the glass (cup)"],
    ["la taza", "the cup"],
    ["la servilleta", "the napkin"],
    ["la copa", "the cup"],
    ["la cuchara", "spoon"],
    ["el plato", "plate"],
    ["el tenedor", "fork"],
    ["el cuchillo", "knife"],
];

const relative_pronouns = [
    ["¿Dónde está la cafetera que compré?", "Where is the coffee maker that I bought?"],
    ["El hombre que limpia es Pedro.", "The man who is cleaning is Pedro."],
    ["¿Son las chicas de quienes me hablaste la semana pasada?", "Are they the girls that you told me about last week?"],
    ["Eva, a quien conocí anoche, es mi nueva vecina.", "Eva, whom I met last night, is my new neighbor."],
    ["Lola, a quien es cubana, es médica.", "Lola, who is Cuban, is a doctor."],
    ["Su tía, que es alemana, ya llegó.", "His aunt, who is German, already arrived."],
    ["Lo que me molesta es el calor.", "What bothers me is the heat."],
    ["Lo que quiero es una casa.", "What I want is a house."],
    ["Este supermercado tiene todo lo que necesito.", "This supermarket has everything I need."],
    ["A Samuel no le gustó lo que le dijo Violeta.", "Samuel didn't like what Violet said to him."],
];

const ud_uds_commands = [
    ["Hable con ellos, don Francisco.", "Talk with them, Don Francisco."],
    ["Laven los platos ahora mismo.", "Wash the dishes right now."],
    ["Coma frutas y verduras.", "Eat fruits and vegetables."],
    ["Beban menos té y café.", "Drink less tea and coffee."],
    ["Oiga, don Manolo...", "Listen, Don Manolo..."],
    ["Ponga la mesa, por favor.", "Set the table, please."],
    ["¡Salga inmediatamente!", "Leave immediately!"],
    ["Hagan la cama antes de salir.", "Make the bed before leaving."],
    ["No ponga las maletas en la cama.", "Don't put the suitcases on the bed."],
    ["No ensucien los sillones.", "Don't dirty the armchairs."],
    ["Muéstrele usted la foto a su amigo.", "Show the photo to your friend."],
    ["Tomen ustedes esta mesa.", "Take this table."],
];

const present_subjunctive = [
    ["Es mejor que cenemos en casa.", "It is better to have dinner at home."],
    ["Es importante que visites las casas colgadas de Cuenca.", "It is important that you visit the hanging houses in Cuenca."],
    ["Señora, es urgente que saque el diente. Tiene una infección.", "Ma'am, it is urgent that you pull the tooth. You have an infection."],
    ["Es malo que Ana les dé tantos dulces a los niños.", "It is bad that Ana gives so much candy to the children."],
    ["Es necesario que lleguen a la una de la tarde.", "It is necessary that you arrive at one o'clock in the afternoon."],
    ["Es importante que acostemos temprano.", "It is important to go to bed early."],
    ["Es importante que coman más verduras", "It is important that they eat more vegetables."],
    ["No, es mejor que salgamos a comer.", "No, it's better if we go out to eat."],
    ["Y yo creo que es Bueno que vaya a madrid después.", "And I think it's good for me to go to Madrid afterwards."],
    ["En mi opinion, no es necesario que durmamos tanto.", "In my opinion, it is not necessary for us to sleep so long."],
    ["¿Ah, sí? ¿Es necesario que me tome un antibiótico también?", "Is it necessary for me to take an antibiotic too?"],
    ["Para llegar a tiempo, no es necesario que almorcemos temprano.", "In order to be on time, we don't need to have an early lunch."],
]

const subjunctive_with_verbs_of_will_and_influence = [
    ["Enrique quiere que salgamos a cenar.", "Enrique wants us to go out to dinner."],
    ["Paola prefiere que cenemos en casa.", "Paola prefers that we have dinner at home."],
    ["Te aconsejo que estudies.", "I advise you to study."],
    ["Le sugiero que vaya a casa.", "I suggest that he go home."],
    ["Les recomiendo que barran el suelo.", "I recommend that you sweep the floor."],
    ["Le ruego que no venga.", "I'm begging him not to come."],
    ["Ella les prohíbe que miren la televisión.", "She prohibits them from watching TV."],
    ["Nos prohiben que nademos en la piscina.", "They prohibit that we swim in the swimming pool."],
    ["No quiero sacudir los muebles.", "I don't want to dust the furniture."],
    ["Paco prefiere descansar.", "Paco prefers to rest."],
    ["Es importante sacar la basura.", "It's important to take out the trash."],
    ["No es necesario quitar la mesa.", "It's not necessary to clear the table."],
]

const la_naturaleza = [
    ["el animal", "animal"],
    ["el bosque (tropical)", "(tropical; rain) forest"],
    ["el desierto", "desert"],
    ["la naturaleza", "nature"],
    ["la planta", "plant"],
    ["la selva, la jungla", "jungle"],
    ["la tierra", "land; soil"],
    ["el cielo", "sky"],
    ["la estrella", "star"],
    ["la luna", "moon"],
    ["el calentamiento global", "global warming"],
    ["el cambio climático", "climate change"],
    ["conservación", "conservation"],
    ["la contaminación (del aire; del agua)", "(air; water) pollution"],
    ["la deforestación", "deforestation"],
    ["la ecología", "ecology"],
    ["el/la ecologista", "ecologist"],
    ["el ecoturismo", "ecotourism"],
    ["la energía (nuclear; solar)", "(nuclear; solar) energy"],
    ["la extinción", "extinction"],
    ["la fábrica", "factory"],
    ["el medio ambiente", "environment"],
    ["el peligro", "danger"],
    ["el recurso natural", "natural resource"],
    ["la solución", "solution"],
    ["el gobierno", "government"],
    ["la ley", "law"],
    ["la (sobre)población", "(over)population"],
    ["ecologista", "ecological"],
    ["puro/a", "pure"],
    ["renovable", "renewable"],
    ["el ave, el pájaro", "bird"],
    ["el cráter", "crater"],
    ["el volcán", "volcano"],
    ["el pez (sing.), los peces (pl.)", "fish"],
    ["la vaca", "cow"],
    ["el árbol", "tree"],
    ["la hierba", "grass"],
    ["la flor", "flower"],
    ["el perro", "dog"],
    ["el gato", "cat"],
    ["el sol", "sun"],
    ["la nube", "cloud"],
    ["el valle", "valley"],
    ["el sendero", "path"],
    ["el lago", "lake"],
    ["la piedra", "stone"],
    ["el río", "river"],
    ["El reciclaje", "recycling (n.)"],
    ["el envase de plástico", "plastic container"],
    ["Recicla la lata de aluminio. (reciclar)", "She recycles the aluminum can."],
    ["Recoge la botella de vidrio. (recoger)", "He picks up the glass bottle."],
    ["cazar", "to hunt"],
    ["conservar", "to conserve"],
    ["contaminar", "to pollute"],
    ["controlar", "to control"],
    ["cuidar", "to take care of"],
    ["dejar de (+ inf.)", "to stop (doing something)"],
    ["desarrollar", "to develop"],
    ["descubrir", "to discover"],
    ["destruir", "to destroy"],
    ["estar afectado/a (por)", "to be affected (by)"],
    ["estar contaminado/a", "to be polluted"],
    ["evitar", "to avoid"],
    ["mejorar", "to improve"],
    ["proteger", "to protect"],
    ["reducir", "to reduce"],
    ["resolver [o:ue]", "to resolve; to solve"],
    ["respirar", "to breathe"],
]

const the_subjunctive_with_verbs_of_emotion = [
    ["Nos alegramos de que te gusten las flores.", "We are happy that you like the flowers."],
    ["Temo que Ana no pueda ir mañana con nosotros.", "I'm afraid that Ana won't be able to go with us tomorrow."],
    ["Siento que tú no puedas venir mañana.", "I'm sorry that you can't come tomorrow."],
    ["Le sorprende que Juan sea tan joven.", "It surprises him that Juan is so young."],
    ["Me molesta que la gente no recicle el plástico.", "It bothers me that people don't recycle plastic."],
    ["Es triste que tengamos problemas como el cambio climático.", "It's sad that we have problems like climate change."],
    ["Temo llegar tarde.", "I'm afraid I'll arrive late."],
    ["Temo que mi novio llegue tarde.", "I'm afraid my boyfriend will arrive late."],
    ["Ojalá (que) se conserven nuestros recursos naturales.", "I hope (that) our natural resources will be conserved."],
    ["Ojalá (que) recojan la basura hoy.", "I hope (that) they collect the garbage today."],
]

const the_subjunctive_with_doubt_disbelief_and_denial = [
    ["El gobierno niega que el agua esté contaminada.", "The government denies that the water is contaminated."],
    ["Es probable que haya menos bosques y selvas en el futuro.", "It's probable that there will be fewer forests and jungles in the future."],
    ["Dudo que el gobierno resuelva el problema.", "I doubt that the government will solve the problem."],
    ["No es verdad que mi hermano estudie ecología.", "It's not true that my brother studies ecology."],
    ["No negamos que hay demasiados carros en las carreteras.", "We don't deny that there are too many cars on the highways"],
    ["No hay duda de que el Amazonas es uno de los ríos más largos.", "There is no doubt that the Amazon is one of the longest rivers."],
    ["Es verdad que Colombia es un país bonito.", "It's true that Colombia is a beautiful country."],
    ["Es obvio que las ballenas están en peligro de extinción.", "It's obvious that whales are in danger of extinction."],
    ["Creo que debemos usar exclusivamente la energía solar.", "I believe we should use solar energy exclusively."],
    ["No creo que haya vida en el planeta Marte.", "I don't believe that there is life on the planet Mars."],
    ["Quizás haga sol mañana.", "Perhaps it will be sunny tomorrow."],
    ["Tal vez veamos la luna esta noche.", "Perhaps we will see the moon tonight."],
]
const the_subjunctive_with_conjunctions = [
    ["Voy a dejar a un recado en caso de que Gustavo me llame.", "I'm going to leave a message in case Gustavo calls me."],
    ["Voy al supermercado para que tengas algo de comer.", "I'm going to the store so that you'll have something to eat."],
    ["Algunos animales van a morir a menos que haya leyes para protegerlos.", "Some animals are going to die unless there are laws to protect them."],
    ["Ellos nos llevan a la selva para que veamos las plantas tropicales.", "They are taking us to the jungle so that we may see the tropical plants."],
    ["Te llamamos antes de salir de la casa.", "We will call you before leaving the house."],
    ["Te llamamos mañana antes de que salgas.", "We will call you tomorrow before you leave."],
    ["Vamos a resolver el problema cuando desarrollemos nuevas tecnologías.", "We are going to solve the problem when we develop new technologies."],
    ["Después de que ustedes tomen sus refrescos, reciclen las botellas.", "After you drink your soft drinks, recycle the bottles."],
    ["Contaminan los ríos cuando construyen nuevos edificios.", "They pollute the rivers when they build new buildings."],
    ["Contaminaron el río cuando construyeron ese edificio.", "They polluted the river when they built that building."],
]

const en_la_ciudad = [
["la frutería", "fruit store"],
["la heladería", "ice cream shop"],
["la pastelería", "pastry shop"],
["la pescadería", "fish market"],
["la cuadra", "(city) block"],
["la dirección", "address"],
["la esquina", "corner"],
["el estacionamiento", "parking lot"],
["derecho", "straight (ahead)"],
["enfrente de", "opposite; facing"],
["hacia", "toward"],
["cruzar", "to cross"],
["doblar", "to turn"],
["hacer diligencias", "to run errands"],
["quedar", "to be located"],
["el cheque (de viajero)", "(traveler's) check"],
["la cuenta corriente", "checking account"],
["la cuenta de ahorros", "savings account"],
["ahorrar", "to save (money)"],
["cobrar", "to cash (a check)"],
["depositar", "to deposit"],
["firmar", "to sign"],
["llenar (un formulario)", "to fill out (a form)"],
["pagar a plazos", "to pay in installments"],
["pagar al contado / en efectivo", "to pay in cash"],
["pedir prestado/a", "to borrow"],
["pedir un préstamo", "to apply for a loan"],
["ser gratis", "to be free of charge"],
["la peluquería / el salón de belleza", "hair salon"],
["el banco", "bank"],
["el supermercado", "supermarket"],
["la panadería", "bakery"],
["la joyería", "jewelry store"],
["el cajero automático", "ATM"],
["Indica cómo llegar. (indicar)", "She indicates the directions."],
["Está perdida. (estar)", "She is lost."],
["el letrero", "the sign"],
["la carnicería", "butcher shop"],
["la zapatería", "shoe store"],
["la lavandería", "laundromat"],
["norte", "north"],
["este", "east"],
["sur", "south"],
["oeste", "west"],
["la estampilla / el sello", "stamp"],
["Hacen cola. (hacer)", "They queue."],
["Echa una carta al buzón. (echar)", "He drops a letter in the mailbox."],
["Manda/Envía un paquete. (mandar, enviar)", "She sends a package."],
["el sobre", "envelope"],
["el cartero", "postman"],
["el correo", "letter"],

]


const the_subjunctive_in_adjective_clauses = [
["Necesito el libro que tiene información sobre Venezuela.", "I need the book that has information about Venezuela."],
["Quiero vivir en esta casa que tiene jardín.", "I want to live in this house that has a garden."],
["En mi barrio, hay una heladería que vende helado de mango.", "In my neighborhood, there's an ice cream shop that sells mango ice cream."],
["Necesito un libro que tenga información sobre Venezuela.", "I need a book that has information about Venezuela."],
["Quiero vivir en una casa que tenga jardín.", "I want to live in a house that has a garden."],
["En mi barrio no hay ninguna heladería que venda helado de mango.", "In my neighborhood, there is no ice cream shop that sells mango ice cream."],
["Quiero ir al supermercado que vende productos venezolanos.", "I want to go to the supermarket that sells Venezuelan products."],
["Busco al profesor que enseña japonés.", "I'm looking for the professor who teaches Japanese."],
["Conozco a alguien que va a esa peluquería.", "I know someone who goes to that beauty salon."],
["Tengo un amigo que vive cerca de mi casa.", "I have a friend who lives near my house."],
["Necesitamos un empleado que sepa usar computadoras.", "We need an employee who knows how to use computers."],
["Buscamos a alguien que pueda cocinar.", "We're looking for someone who can cook."],
["Necesitamos al empleado que sabe usar computadoras.", "We need the employee who knows how to use computers."],
["No conocemos a nadie que pueda cocinar.", "We don't know anyone who can cook."],
["¿Hay un parque que esté cerca de nuestro hotel?", "Is there a park that's near our hotel?"],
["Sí, hay un parque que está muy cerca del hotel.", "Yes, there's a park that's very near the hotel."],
    
];

const nosotros_as_commands = [
    ["Crucemos la calle.", "Let's cross the street."],
    ["No crucemos la calle.", "Let's not cross the street."],
    ["Vamos a cruzar la calle.", "Let's cross the street. (future)"],
    ["Vamos a trabajar mucho.", "We're going to work a lot."],
    ["Vamos a la pescadería.", "Let's go to the fish market."],
    ["No vayamos a la pescadería.", "Let's not go to the fish market."],
    ["Firmemos el cheque.", "Let's sign the check."],
    ["Firmémoslo.", "Let's sign it. (the check)"],
    ["Escribamos a Ana y Raúl.", "Let's write Ana and Raul."],
    ["No les paguemos el préstamo.", "Let's not pay the loan."],
    ["No se lo digamos a ellos.", "Let's not tell them."],
]

    const past_participles_used_as_adjectives = [
["In the entrance, there are some signs written in Spanish.", "En la entrada hay algunos letreros escritos en español."],
 
["We have the table set and dinner made.", "Tenemos la mesa puesta y la cena hecha."],
 
["Today my favorite hair salon is closed.", "Hoy mi peluquería favorita está cerrada."],
 
["So, I go to another beauty salon that is open every day.", "Por eso, voy a otro salón de belleza que está abierto todos los días."],
 
["It is located in Plaza Bolivar, a very well known square.", "Queda en la Plaza Bolívar, una plaza muy conocida."],
 
["All products and services of this store are described in a catalog.", "Todos los productos y servicios de esta tienda están descritos en un catálogo."],
 
["The name of the salon is written on the sign and on the sidewalk.", "El nombre del salón está escrito en el letrero y en la acera."],
 
["When this diligence is done, I need to stop by the bank.", "Cuando esta diligencia esté hecha, necesito pasar por el banco."],
 
["My bed is always made.", "Mi cama siempre está hecha."],
 
["My problems are always solved.", "Mis problemas siempre están resueltos."],
 ];


const el_bienestar = [
["adelgazar", "to lose weight; to slim down"],
["aliviar el estrés", "to reduce stress"],
["aliviar la tensión", "to reduce tension"],
["apurarse, darse prisa", "to hurry; to rush"],
["aumentar de peso, engordar", "to gain weight"],
["calentarse (e:ie)", "to warm up"],
["disfrutar (de)", "to enjoy; to reap the benefits (of)"],
["entrenarse", "to practice; to train"],
["estar a dieta", "to be on a diet"],
["estar en buena forma", "to be in good shape"],
["hacer gimnasia", "to work out"],
["llevar una vida sana", "to lead a healthy lifestyle"],
["mantenerse en forma", "to stay in shape"],
["sufrir muchas presiones", "to be under a lot of pressure"],
["tratar de <i>(+ inf.)</i>", "to try (to do something)"],
["la droga", "drug"],
["el/la drogadicto/a", "drug addict"],
["activo/a", "active"],
["débil", "weak"],
["en exceso", "in excess; too much"],
["flexible", "flexible"],
["fuerte", "strong"],
["sedentario/a", "sedentary; related to sitting"],
["tranquilo/a", "calm; quiet"],
["el bienestar", "well-being"],
["el teleadicto", "TV addict"],
["Hace ejercicios de estiramiento. (hacer)", "She does stretching exercises."],
["la clase de ejercicios aeróbicos", "aerobic exercise class"],
["Suda. (sudar)", "She sweats."],
["Hace ejercicio. (hacer)", "She exercises."],
["el entrenador", "coach"],
["el músculo", "muscle"],
["la cinta caminadora", "treadmill"],
["No fumar.", "No smoking."],
["el masaje", "the massage"],
["Hacen ejercicios aeróbicos. (hacer)", "They do aerobic exercise."],
["Levanta pesas (levantar)", "He lifts weights."],
["La nutrición", "nutrition"],
["la grasa", "fat"],
["la proteína", "protein"],
["los minerales", "minerals"],
["las vitaminas", "vitamins"],
["el colesterol", "cholesterol"],
["la bebida alcohólica", "alcoholic beverage"],
["la cafeína", "caffeine"],
["la caloría", "calorie"],
["la merienda", "afternoon snack"],
["el/la nutricionista", "nutritionist"],
["comer una dieta equilibrada", "to eat a balanced diet"],
["consumir alcohol", "to consume alcohol"],
["descafeinado/a", "decaffeinated"],

]

const present_perfect = [
["Tú no has aumentado de peso.", "You haven't gained weight."],
["Yo ya he leído esos libros.", "I've already read those books."],
["¿Ha asistido Juan a la clase de yoga?", "Has Juan attended the yoga class?"],
["Hemos conocido al entrenador.", "We have met the trainer."],
["Clara ha abierto las ventanas.", "Clara has opened the windows."],
["Yo ha cerrado la puerta del gimnasio.", "I've closed the door to the gym."],
["Las ventanas están abiertas.", "The windows are open."],
["La puerta del gimnasio está cerrada.", "The door to the gym is closed."],
["He trabajado cuarenta horas esta semana.", "I have worked forty hours this week."],
["¿Cuál es el último libro que has leído?", "What is the last book that you have read?"],
["Siempre hemos vivido en Bolivia.", "We have always lived in Bolivia."],
["Usted nunca ha venido a mi oficina.", "You have never come to my office."],
["Yo no he comido la merienda.", "I haven't eaten the snack."],
["¿Por qué no la has comido?", "Why haven't you eaten it?"],
["Susana ya se ha entrenado.", "Susana has already practiced."],
["Ellos no lo han terminado.", "They haven't finished it."],
["Tengo muchos amigos.", "I have a lot of friends."],
["He tenido mucho éxito.", "I have had a lot of success."],
["Ha habido muchos problemas con el nuevo profesor.", "There have been a lot of problems with the new professor."],
["Ha habido un accidente en la calle Central.", "There has been an accident on Central Street."],

]


const conditional_perfect = [
["Antes de 2012, había vídeo en la paz", "Before 2012, I had lived in La Paz"],
["Cuando llegamos, Luis ya había salido", "When we arrived, Luis had already left"],
["Ella ya había salido cuando llamaron", "She had already left when they called"],
["Cuando llegué, Raúl ya se había ido a la cama", "When I arrived, Raul had already gone to bed"],
["Antes de esto ano nunca había estudiado química", "Before this year I had never studied chemistry"],
["Luis me había llamado antes de venir", "Luis had called me before he came"],
["Nosotros ya habíamos cenado cuando nos llamaron", "We had already had dinner when they called us"],
["Antes de tomar esta clase, yo no había estudiado nunca el español", "Before taking this class, I had never studied Spanish"],
["Antes de ir a México, ellos nunca habían ido a otro país", "Before going to Mexico, they had never been to another country"],
["Eduardo nunca se había entrenado tanto en el invierno", "Eduardo had never trained so much in the winter"],


]


const past_perfect_subjunctive = [
    ["Espero que duermas bien", "I hope you slept well"],
    ["Espero que hayas dormido bien", "I hope that you have slept well"],
    ["No creo que aumente de peso", "I don’t think he will gain weight"],
    ["No creo que haya aumentado de peso", "I don’t think he has gained weight"],
    ["Me alegro de que ustedes se hayan reído tanto esta tarde", "I’m glad that you have laughed so much this afternoon"],
    ["Dudo que tú te hayas divertido mucho con tu suegra", "I doubt that you have enjoyed yourself much with your mother-in-law"],
    ["Me gusta que ustedes hayan dicho la verdad", "I like that you have told the truth"],
    ["No creo que tú hayas comido tanto", "I don’t think you have eaten that much"],
    ["Es imposible que usted haya podido hacer tal cosa", "It is impossible that you have done such a thing"],
    ["Me alegro de que tú y yo hayamos merendado juntas", "I am glad that you have snacked together"],
]


const el_mundo_del_trabajo = [
["el/la abogado/a", "lawyer"],
["el actor, la actriz", "actor"],
["el/la consejero/a", "counselor; advisor"],
["el/la contador(a)", "accountant"],
["el/la corredor(a) de bolsa", "stockbroker"],
["el/la diseñador(a)", "designer"],
["el/la electrista", "electrician"],
["el/la gerente", "manager"],
["el hombre/la mujer de negocios", "businessperson"],
["el/la jefe/a", "boss"],
["el/la maestro/a", "teacher"],
["el/la político/a", "politician"],
["el/la psicólogo/a", "psychologist"],
["el/la secretario/a", "secretary"],
["el/la técnico/a", "technician"],
["el ascenso", "promotion"],
["el aumento de sueldo", "raise"],
["la carrera", "career"],
["la compañía, la empresa", "company; firm"],
["el empleo", "job; employment"],
["los negocios", "business; commerce"],
["la ocupación", "occupation"],
["el oficio", "trade"],
["la profesión", "profession"],
["la reunión", "meeting"],
["el teletrabajo", "telecommuting"],
["el trabajo", "job; work"],
["la videoconferencia", "videoconference"],
["dejar", "to quit; to leave behind"],
["despedir (e:i)", "to fire"],
["invertir (e:ie)", "to invest"],
["renunciar (a)", "to resign (from)"],
["tener éxito", "to be successful"],
["comercial", "commercial; business-related"],
["el carpintero", "carpenter"],
["el pintor", "painter"],
["el arquitecto", "architect"],
["el peluquero", "hair stylist"],
["el científico", "scientist"],
["la arqueóloga", "archæologist"],
["el cocinero", "chef"],
["la reportera", "reporter"],
["el bombero", "firefighter"],
["el anuncio", "advertisement"],
["el/la aspirante", "candidate; applicant"],
["los beneficios", "benefits"],
["el currículum", "résumé"],
["la entrevista", "interview"],
["el/la entrevistador(a)", "interviewer"],
["el puesto", "position; job"],
["el salario, el sueldo", "salary"],
["la solicitud (de trabajo)", "(j*b) application"],
["contratar", "to hire"],
["entrevistar", "to interview"],
["ganar", "to earn"],
["obtener", "to obtain; to get"],
["solicitar", "to apply (for a j*b)"],

]


const info = [
    en_el_consultorio,
    imperfect_tense,
    preterite_and_imperfect,
    constructions_with_se,
    adverbs,

    la_tecnología,
    familiar_commands,
    por_and_para,
    reciprocal_reflexives,
    stressed_possessive_adjectives_and_pronouns,
    
    la_vivienda,
    relative_pronouns,
    ud_uds_commands,
    present_subjunctive,
    subjunctive_with_verbs_of_will_and_influence,

    la_naturaleza,
    the_subjunctive_with_verbs_of_emotion,
    the_subjunctive_with_doubt_disbelief_and_denial,
    the_subjunctive_with_conjunctions,

    en_la_ciudad,
    the_subjunctive_in_adjective_clauses,
    nosotros_as_commands,
    past_participles_used_as_adjectives,

    el_bienestar,
    present_perfect,
    conditional_perfect,
    past_perfect_subjunctive,

    el_mundo_del_trabajo,
]
