const en_el_consultorio = [
    ["la clínica", "clinic"],
    ["el consultorio", "doctor's office"],
    ["el/la dentista", "dentist"],
    ["el examen médico", "physical exam"],
    ["la farmacia", "pharmacy"],
    ["el hospital", "hospital"],
    ["la operación", "operation"],
    ["la sala de emergencias", "emergency room"],
    ["el cuerpo", "body"],
    ["el oído", "(sense of) hearing; inner ear"],
    ["el accidente", "accident"],
    ["la salud", "health"],
    ["el sintoma", "symptom"],
    ["caerse", "to fall (down) "],
    ["darse con", "to bump into; to run into "],
    ["doler (o:ue)", "to hurt "],
    ["enfermarse", "to get sick "],
    ["estar enfermo/a", "to be sick "],
    ["poner una inyección", "to give an injection "],
    ["recetar", "to prescribe "],
    ["romperse (la pierna)", "to break (one's leg) "],
    ["sacar(se) un diente", "to have a tooth removed "],
    ["sufrir una enfermedad", "to suffer an illness "],
    ["torcerse (o:ue) (el tobillo)", "to sprain (one's ankle) "],
    ["toser", "to cough "],
    ["el dolor (de cabeza)", "(head)ache; pain"],
    ["la gripe", "flu"],
    ["el resfriado", "cold"],
    ["la tos", "cough"],
    ["congestionado/a", "congested; stuffed up"],
    ["embarazada", "pregnant"],
    ["grave", "grave; serious"],
    ["mareado/a", "dizzy; nauseated"],
    ["médico/a", "medical"],
    ["saludable", "healthy"],
    ["sano/a", "healthy"],
    ["tener dolor (m.)", "to have pain "],
    ["tener fiebre", "to have a fever "],
    ["el antibiótico", "antibiotic"],
    ["la aspirina", "aspirin"],
    ["la pastilla", "pill; tablet"],
    ["la receta", "prescription"],
    ["el paciente", "patient"],
    ["la cabeza", "head"],
    ["la oreja", "ear"],
    ["el cuello", "neck"],
    ["la boca", "mouth"],
    ["la garganta", "throat"],
    ["el estómago", "stomach"],
    ["la naríz", "nose"],
    ["el corazón", "heart"],
    ["el dedo", "finger"],
    ["la rodilla", "knee"],
    ["el pie", "foot"],
    ["el dedo de pie", "toe"],
    ["el radiografía", "xray"],
    ["el hueso", "bone"],
    ["la enfermera", "nurse"],
    ["estornuda", "sneeze"],
    ["toma la temperatura", "taking temperature"],
    ["el brazo", "arm"],
]


const imperfect_tense = [
    ["Entendíamos japonés.", "We used to understand Japanese."],
    ["El camarero les servía el café.", "The waiter was serving them coffee."],
    ["A Javier le dolía el tobillo.", "Javier's ankle was hurting."],
    ["¿Qué te pasó?", "What happened to you?"],
    ["Me torcí el tobillo.", "I sprained my ankle."],
    ["¿Dónde vivías de niño?", "Where did you live as a child?"],
    ["Vivía en San José.", "I lived in San José."],
    ["Íbamos al parque los domingos.", "We used to go to the park on Sundays."],
    ["Yo leía mientras él estudiaba.", "I was reading while he was studying."],
    ["Era alto y guapo.", "He was tall and handsome."],
    ["Quería mucho a su familia.", "He loved his family very much."],
    ["Eran las tres y media.", "It was 3:30."],
    ["Los niños tenían seis años.", "The children were six years old."],
]


const constructions_with_se = [
    ["Se habla español en Costa Rica.", "Spanish is spoken in Costa Rica."],
    ["Se hacen operaciones aquí.", "They perform operations here."],
    ["Se puede leer en la sala de espera.", "You can read in the waiting room."],
    ["Se necesitan medicinas enseguida.", "They need medicine right away."],
    ["Se me perdió el teléfono de la farmacia.", "I lost the pharmacy's phone number."],
    ["Se nos olvidaron los pasajes.", "We forgot the tickets."],
    ["El médico dejó caer la aspirina.", "The doctor dropped the aspirin."],
    ["A mí se me cayeron los cuadernos.", "I dropped the notebooks."],
    ["Al paciente se le perdió la receta.", "The patient lost his prescription."],
    ["A ustedes se les quedaron los libros en casa.", "You left the books at home."],
]


const preterite_and_imperfect = [
    ["Sandra se rompió la pierna.", "Sandra broke her leg."],
    ["Fueron a Buenos Aires ayer.", "They went to Buenos Aires yesterday."],
    ["La película empezó a las nueve.", "The movie began at nine o'clock."],
    ["Ayer terminé el proyecto para la clase de química.", "Yesterday I finished the project for chemistry class."],
    ["La doctora me miró los oídos, me hizo unas preguntas y escribió la receta.", "The doctor looked in my ears, asked me some questions, and wrote the prescription."],
    ["Me di con la mesa me caí y me lastimé el pie.", "I bumped into the table, I fell, and I injured my foot."],
    ["Sandra esperaba al doctor.", "Sandra was waiting for the doctor."],
    ["El médico se preocupaba por sus pacientes.", "The doctor worried about his patients."],
    ["Cuando era joven, jugaba al tenis.", "When I was young, I used to play tennis."],
    ["De niño, Eduardo se enfermaba con mucha frecuencia.", "As a child, Eduardo used to get sick very frequently."],
    ["La chica quería descansar. Se sentía mal y tenía dolor de cabeza.", "The girl wanted to rest. She felt ill and has a headache."],
    ["Ellos eran altos y tenían ojos verdes.", "They were tall and had green eyes."],
    ["Estábamos felices de ver a la familia.", "We were happy to see our family."],
    ["Miraba la tele cuando sonó el teléfono.", "I was watching TV when the phone rang."],
    ["Felicia leía el periódico cuando llegó Ramiro.", "Felicia was reading the newspaper when Ramiro arrived."],
]

const adverbs = [
    ["Maira dibuja maravillosamente.", "Maira draws wonderfully."],
    ["Sergio está casi siempre ocupado.", "Sergio is almost always busy."],
    ["La cita era a las dos, pero llegamos tarde.", "The appointment was at two o'clock, but we were late."],
    ["El problema fue que ayer se nos dañó el despertador.", "The problem was that yesterday our alarm clock was damaged."],
    ["La recepcionista no se enojó porque sabe que normalmente llego a tiempo.", "The receptionist did not get angry because she knows I usually arrive on time."],
    ["Por lo menos el doctor estaba listo.", "At least the doctor was ready."],
    ["Apenas tuvimos que esperar cinco minutos.", "We barely had to wait five minutes."],
    ["El doctor dijo que nuestra hija Claire necesitaba cambiar su rutina diaria inmediatamente.", "The doctor said that our daughter Claire needed to change her daily routine immediately."],
    ["El doctor nos explicó bien las recomendaciones del Secretario de Sanidad sobre la salud de los jóvenes.", "The doctor explained to us the recommendations of the Minister of Health regarding the health of young people."],
    ["Afortunadamente nos dijo que Claire estaba bien, pero tenía que hacer más ejercicio y comer mejor.", "Fortunately he told us that Claire was doing well, but she needed to exercise more and eat better."],
]

const la_tecnología = [
    ["la cámara digital/de video", 'digital (video) camera'],
    ['el canal', '(TV) channel'],
    ['el cibercafé', 'cybercafé'],
    ["el correo de voz", "voice mail"],
    ["el estéreo", "stereo"],
    ["el fax", "fax (machine)"],
    ["la pantalla táctil", "touch screen"],
    ["el reproductor de CD", "CD player"],
    ["la televisión por cable", "cable television"],
    ["el video", "video"],
    ["el archivo", "file"],
    ["la arroba", "@ symbol"],
    ["el blog", "blog"],
    ["la conexión inalámbrica", "wireless connection"],
    ["la dirección electrónica", "e-mail address"],
    ["Internet", "Internet"],
    ["el mensaje de texto", "text message"],
    ["la página principal", "home page"],
    ["el programa de computación", "software"],
    ["la red", "network; Web"],
    ["el sitio web", "website"],
    ["apagar", "to turn off"],
    ["borrar", "to erase"],
    ["descargar", "to download"],
    ["escanear", "to scan"],
    ["funcionar", "to work"],
    ["grabar", "to record"],
    ["guardar", "to save"],
    ["imprimir", "to print"],
    ["llamar", "to call"],
    ["navegar (en Internet)", "to surf (the Internet)"],
    ["poner, prender", "to turn on"],
    ["sonar (o:ue)", "to ring"],
    ["descompuesto/a", "not working; out of order"],
    ["lento/a", "slow"],
    ["lleno/a", "full"],
    ["el televisor", "television"],
    ["la pantalla", "the screen"],
    ["el reproductor de DVD", "DVD player"],
    ["la impresora", "printer"],
    ["la computadora (portátil)", "computer (laptop)"],
    ["el monitor", "the monitor"],
    ["el ratón", "(computer) mouse"],
    ["el (teléfono) celular", "cell phone"],
    ["el teclado", "keyboard"],
    ["el cederrón", "CD (CD-ROM)"],
    ["el control remoto", "the remote control"],
    ["el reproductor de MP3", "the MP3 player"],
    ["el disco compacto", "compact disc"],
    ["la autopista, la carretera", "highway"],
    ["la calle", "street"],
    ["la circulación, el tráfico", "traffic"],
    ["el garaje, el taller (mecánico)", "(mechanic's) garage; repair shop"],
    ["la licencia de conducir", "driver's license"],
    ["el/la mecánico/a", "mechanic"],
    ["la policía", "police (force)"],
    ["la velocidad máxima", "speed limit"],
    ["arrancar", "to start"],
    ["arreglar", "to fix; to arrange"],
    ["bajar(se) de", "to get off of/out of (a vehicle)"],
    ["conducir manejar", "to drive"],
    ["estacionar", "to park"],
    ["parar", "to stop"],
    ["subir(se) a", "to get on/into (a vehicle)"],
    ["el capó, el cofre", "the hood (of a car)"],
    ["el parabrisas", "the windshield"],
    ["Revisa el aceite. (revisar)", "He checks the oil (to check)"],
    ["el carro, el coche", "car"],
    ["Llena el tanque. (llenar)", "He fills the tank (to fill)"],
    ["el radio", "the radio (physical object)"],
    ["la gasolina", "the gasoline"],
    ["el baúl", "the trunk"],
    ["el navegador GPS", "the GPS navigator"],
    ["el volante", "the steering wheel"],
    ["la llanta", "the tire"],
]

const familiar_commands = [
    ["Guarda el documento antes de cerrarlo.", "Save the document before closing it."],
    ["Imprime tu tarea para la clase de inglés.", "Print your homework for English class."],
    ["¡Sal ahora mismo!", "Leave at once!"],
    ["Haz los ejercicios.", "Do the exercises."],
    ["Ve al cibercafé con Yolanda.", "Go to the cybercafé with Yolanda."],
    ["Ve ese programa... es muy interesante.", "See that program... it's very interesting."],
    ["Héctor, no pares el carro aquí.", "Héctor, don't stop the car here."],
    ["No prendas la computadora todavía.", "Don't turn on the computer yet."],
    ["No pongas el cederrón en la computadora.", "Don't put the CD-ROM in the computer."],
    ["No conduzcas tan rápido.", "Don't drive so fast."],
    ["No pierdas tu celular.", "Don't lose your cell phone."],
    ["No vuelvas a esa gasolinera.", "Don't go back to that gas station."],
    ["No repitas las instrucciones.", "Don't repeat the instructions."],
]

const por_and_para = [
    ["La excursión nos llevó por el centro.", "The tour took us through downtown."],
    ["Mis amigos van para el estadio.", "My friends are going to the stadium."],
    ["Ana navegó la red por dos horas.", "Ana surfed the net for two hours."],
    ["Tengo que escribir un esayo para mañana.", "I have to write an essay by tomorrow."],
    ["Llegué a casa tarde por el tráfico.", "I got home late because of the traffic."],
    ["Estoy preparando una sorpresa para Eduardo.", "I'm preparing a surprise for Eduardo."],
    ["Pasamos por el parque y por el rio.", "We passed by the park and along the river."],
    ["Estuve en la Patagonia por un mes.", "I was in Patagonia for a month."],
    ["Lo hizo por su familia.", "She did it on behalf of her family."],
    ["Vengo por ti a las ocho.", "I'm coming for you at eight."],
    ["Manuel fue por su cámara digital.", "Manuel went in search of his digital camera."],
    ["Ellos viajan por la autopista.", "They travel by (by way of) the highway."],
    ["Le di dinero por el reproductor de MP3.", "I gave him money for the MP3 player."],
    ["José manejaba a 120 kilómetros por hora.", "José was driving 120 kilometers per hour."],
    ["Salimos para Córdoba el sábado.", "We are leaving for Córdoba on Saturday."],
    ["Él va a arreglar el carro para el viernes.", "He will fix the car by Friday."],
    ["Juan estudia para (ser) mecánico.", "Juan is studying to be a mechanic."],
    ["Es una llanta para el carro.", "It's a tire for the car."],
    ["Compré una impresora para mi abuelo.", "I bought a printer for my grandfather."],
    ["Para un joven, es desmasiado serio.", "For a young person, he is too serious."],
    ["Para mí, esta lección no es difícil.", "For me, this lesson isn't difficult."],
    ["Sara trabaja para Telecom Argentina.", "Sara works for Telecom Argentina."],
    ["Caminé por el parque.", "I walked through the park."],
    ["Caminé para el parque.", "I walked to (toward) the park."],
    ["Trabajó por su padre.", "He worked for (in place of) his father."],
    ["Trabajó para su padre.", "He worked for his father('s company)."],
]

const info = [
    en_el_consultorio,
    imperfect_tense,
    preterite_and_imperfect,
    constructions_with_se,
    adverbs,
    la_tecnología,
    familiar_commands,
    por_and_para
]